export const palette = {
  live: '#C9FF43',
  liveMuted: '#83A92F',
  review: '#FF665E',
  warning: '#F4C95D',
  success: '#6EE7A8',
  info: '#78A8FF',
  text: '#F4F1E9',
  dim: '#9CA2AB',
  faint: '#5C636D',
  rail: '#343A43',
};

export const glyph = {
  bullet: '•',
  check: '✓',
  baseline: '●',
  review: '!',
  blocked: '×',
  changed: '≠',
  same: '=',
  error: '!',
  unknown: '?',
  pending: '·',
  rail: '│',
  arrow: '→',
  route: '─',
  barFull: '━',
  barEmpty: '─',
};
